---
title: Action characters
category: character
---
a biker
a black ops agent
a bodyguard
a bomb squad specialist
a bomber
a brawler
a combat medic
a commando
a covert operative
a crime boss
a criminal mastermind
a demolitions expert
a detective
a double agent
a firearms expert
a fugitive
a gang leader
a guerrilla fighter
a gunslinger
a hacker
a hand-to-hand combat expert
a highwayman
a hitman
a hitman-turned-protector
a hitwoman
a hostage negotiator
a kickboxer
a marksman
a martial artist
a martial arts master
a mercenary
a military commander
a motorcycle racer
a navy seal
a ninja
a paramilitary fighter
a parkour expert
a pilot
a pirate
a police officer
a prison escapee
a prison warden
a private investigator
a race car driver
a riot police officer
a rogue agent
a ruthless killer
a secret agent
a sniper
a soldier
a special forces operator
a spy
a street fighter
a stunt double
a survivalist
a swordsman
a tactical specialist
a thief
a thief-turned-hero
a vigilante
a vigilante justice seeker
an assassin
an elite bodyguard
an ex-convict
an explosives expert
an intelligence officer
an undercover agent
an undercover cop
an urban explorer
