---
title: Action plots
category: plot
---
breaking into a secure location
dealing with a corrupt government or law enforcement
defending against a cyber attack or hacking attempt
defending against a home invasion or siege
defending against a military attack
defending against a supernatural threat
defending against a zombie outbreak
escaping from a burning building or other disaster
escaping from a collapsed building or tunnel
escaping from a dangerous animal attack
escaping from a dangerous maze or labyrinth
escaping from a dangerous prison
escaping from a hazardous environment or extreme weather
escaping from a helicopter crash or other airborne disaster
escaping from a prison break or jailbreak
escaping from a sinking ship or other maritime disaster
infiltrating a cartel or organized crime group
infiltrating a criminal organization
infiltrating a secret laboratory or research facility
infiltrating a secret society or cult
infiltrating a spy or espionage organization
overcoming challenges in a post-apocalyptic world
overcoming personal conflicts to work together
overcoming personal demons or fears
overcoming physical challenges or obstacles
participating in a heist or caper
participating in a high-speed car chase
participating in a high-stakes game or contest
participating in a survival-of-the-fittest competition
preventing a dangerous weapon from falling into the wrong hands
pursuing a fleeing criminal
rescuing a captive from a jungle or wilderness
rescuing a captive or hostage
rescuing a loved one from danger
rescuing a stranded or lost team or crew
rescuing survivors of a natural disaster
robbing a bank or high-security facility
saving a city from destruction
saving a group of people from a dangerous situation
saving a kidnapped vip or important figure
saving the world from a dangerous virus or disease
stealing valuable items or documents
stopping a criminal mastermind from enacting their plan
stopping a dangerous new technology or invention from falling into the wrong hands
stopping a mass murderer or serial killer
stopping a political uprising or revolution
stopping a rogue ai or weapon of mass destruction
stopping a rogue government agency or corporation
stopping a terrorist attack
surviving in a wilderness or jungle
